// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBalMbgwYBAyLROS82dJ2QcgQT-lNaL508',
    appId: '1:1076516562552:web:8acab97b3c94cde450af8d',
    messagingSenderId: '1076516562552',
    projectId: 'djsboxfun-a83c9',
    authDomain: 'djsboxfun-a83c9.firebaseapp.com',
    storageBucket: 'djsboxfun-a83c9.appspot.com',
    measurementId: 'G-7DWG7M6R4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM5Q6xOoJPtB028O8N5Zh6VwZyg_BNEOE',
    appId: '1:1076516562552:android:14185b5e6d5b0ce150af8d',
    messagingSenderId: '1076516562552',
    projectId: 'djsboxfun-a83c9',
    storageBucket: 'djsboxfun-a83c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzUcx06vMkNPQlHNoJY4KhAKIMbcQSCiI',
    appId: '1:1076516562552:ios:5c491ca79a85203b50af8d',
    messagingSenderId: '1076516562552',
    projectId: 'djsboxfun-a83c9',
    storageBucket: 'djsboxfun-a83c9.appspot.com',
    iosBundleId: 'com.techsolutions.djsboxfun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzUcx06vMkNPQlHNoJY4KhAKIMbcQSCiI',
    appId: '1:1076516562552:ios:5c491ca79a85203b50af8d',
    messagingSenderId: '1076516562552',
    projectId: 'djsboxfun-a83c9',
    storageBucket: 'djsboxfun-a83c9.appspot.com',
    iosBundleId: 'com.techsolutions.djsboxfun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBalMbgwYBAyLROS82dJ2QcgQT-lNaL508',
    appId: '1:1076516562552:web:c1365c60e61a5a4850af8d',
    messagingSenderId: '1076516562552',
    projectId: 'djsboxfun-a83c9',
    authDomain: 'djsboxfun-a83c9.firebaseapp.com',
    storageBucket: 'djsboxfun-a83c9.appspot.com',
    measurementId: 'G-VK14BG5C9X',
  );

}